database:
  engine: postgresql://mxk@localhost/testdb
  echo: false
finders:
  - buffer: /home/mxk/foo
    storage: /home/mxk/qux
    blacklist: null
    actions:
      standard: Move
      alternative: Delete
    search_method: scan
    pause: 1
ingesters:
  - plugin:
      name: Gen2Ingest
      config:
        root: /tmp/gen2repo
    file_status: untried
    batch_size: 10
    daemon: true
    pool_size: 1
    pause: 1
logging:
  file: null
  format: "%(asctime)s:%(name)s:%(levelname)s:%(message)s"
  level: WARNING